Repository KipData/KiteSQL, pull requests merged in 2023-12, with the labels that each got.

#104 Alter table
  src/binder/alter_table.rs
  src/binder/create_table.rs
  src/binder/insert.rs
  src/binder/mod.rs
  src/execution/executor/ddl/alter_table/add_column.rs
  src/execution/executor/ddl/alter_table/mod.rs
  src/execution/executor/ddl/mod.rs
  src/execution/executor/mod.rs
  src/optimizer/rule/column_pruning.rs
  src/planner/operator/alter_table/add_column.rs
  src/planner/operator/alter_table/mod.rs
  src/planner/operator/mod.rs
  src/storage/kip.rs
  src/storage/mod.rs
  tests/slt/alter_table.slt
Labels: enhancement

#109 feat: support drop column
  Cargo.toml
  src/binder/alter_table.rs
  src/catalog/table.rs
  src/execution/executor/ddl/alter_table/add_column.rs
  src/execution/executor/ddl/alter_table/drop_column.rs
  src/execution/executor/ddl/alter_table/mod.rs
  src/execution/executor/mod.rs
  src/optimizer/rule/column_pruning.rs
  src/planner/operator/alter_table/drop_column.rs
  src/planner/operator/alter_table/mod.rs
  src/planner/operator/mod.rs
  src/storage/kip.rs
  src/storage/mod.rs
  tests/slt/alter_table.slt
  tests/slt/basic_test.slt
Labels: enhancement

#111 fix(binder): insert column count validation
  src/binder/insert.rs
  src/binder/mod.rs
Labels: bug

#113 docs: update TableCode comments
  src/storage/table_codec.rs
Labels: documentation

#115 Feat: Add args path for main
  Cargo.toml
  src/main.rs
Labels: enhancement

#112 Optimize Sort Executor
  Cargo.toml
  src/binder/aggregate.rs
  src/binder/alter_table.rs
  src/binder/create_table.rs
  src/binder/delete.rs
  src/binder/drop_table.rs
  src/binder/insert.rs
  src/binder/mod.rs
  src/binder/select.rs
  src/binder/truncate.rs
  src/binder/update.rs
  src/catalog/mod.rs
  src/catalog/root.rs
  src/execution/executor/dql/sort.rs
  src/execution/mod.rs
  src/storage/table_codec.rs
  src/types/value.rs
  tests/slt/create.slt
  tests/slt/distinct.slt
  tests/slt/insert.slt
  tests/slt/order_by.slt
Labels: enhancement
