Repository KipData/KiteSQL, pull requests merged in 2023-06, with the labels that each got.

#1 feat(parser):新增parser模块，以及项目目录的搭建
  .github/workflows/ci.yml
  .gitignore
  Cargo.toml
  src/lib.rs
  src/main.rs
  src/parser/mod.rs
  src/parser/rs_parser.rs
Labels: enhancement

#4 *: add issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: documentation

#11 Simpler Catalog implementation
  Cargo.toml
  src/binder/mod.rs
  src/binder/select.rs
  src/catalog/column.rs
  src/catalog/database.rs
  src/catalog/mod.rs
  src/catalog/root.rs
  src/catalog/schema.rs
  src/catalog/table.rs
  src/executor/physical/mod.rs
  src/executor/physical/physical_project.rs
  src/executor/physical/physical_scan.rs
  src/planner/logical_plan_builder.rs
  src/planner/operator/join.rs
  src/planner/operator/scan.rs
  src/types/mod.rs
Labels: invalid
