Repository KipData/KiteSQL, pull requests merged in 2023-07, with the labels that each got.

#20 fix(parser): doc test.
  src/parser/mod.rs
Labels: invalid

#25 feat(doc): change README.md
  README.md
  README_ZH.md
  assets/Untitled 1.png
  assets/Untitled 3.png
  assets/Untitled 4.png
  assets/Untitled 5.png
Labels: documentation

#22 feat(type): use arrow type to support vectorization
  .github/workflows/ci.yml
  .github/workflows/cr.yml
  Cargo.toml
  rust-toolchain
  src/binder/create.rs
  src/binder/expr.rs
  src/binder/mod.rs
  src/binder/select.rs
  src/catalog/column.rs
  src/catalog/mod.rs
  src/catalog/root.rs
  src/catalog/table.rs
  src/db.rs
  src/expression/agg.rs
  src/expression/mod.rs
  src/lib.rs
  src/main.rs
  src/planner/logical_plan_builder.rs
  src/planner/mod.rs
  src/storage/memory.rs
  src/storage/mod.rs
  src/types/errors.rs
  src/types/mod.rs
  src/types/value.rs
Labels: enhancement

#26 feat(volcano_executor): implementing a Simple Volcano Actuator
  Cargo.toml
  rust-toolchain
  src/binder/create.rs
  src/binder/mod.rs
  src/binder/select.rs
  src/catalog/column.rs
  src/catalog/root.rs
  src/catalog/table.rs
  src/db.rs
  src/execution/executor_graph.rs
  src/execution_v1/mod.rs
  src/execution_v1/physical_plan/mod.rs
  src/execution_v1/physical_plan/physical_plan_builder.rs
  src/execution_v1/physical_plan/physical_projection.rs
  src/execution_v1/physical_plan/physical_table_scan.rs
  src/execution_v1/volcano_executor/mod.rs
  src/execution_v1/volcano_executor/projection.rs
  src/execution_v1/volcano_executor/table_scan.rs
  src/expression/array_compute.rs
  src/expression/evaluator.rs
  src/expression/mod.rs
  src/lib.rs
  src/main.rs
  src/parser/mod.rs
  src/planner/logical_create_table_plan.rs
  src/storage/memory.rs
  src/storage/mod.rs
  src/types/mod.rs
  src/types/value.rs
Labels: enhancement

#28 feat(binder): implement `Binder::bind_expr`
  src/binder/aggregate.rs
  src/binder/expr.rs
  src/binder/select.rs
  src/expression/evaluator.rs
  src/expression/mod.rs
  src/storage/memory.rs
Labels: enhancement

#29 feat(insert): support sql insert simple syntax
  src/binder/create_table.rs
  src/binder/insert.rs
  src/binder/mod.rs
  src/binder/select.rs
  src/catalog/column.rs
  src/catalog/table.rs
  src/db.rs
  src/execution/physical/physical_plan_builder.rs
  src/execution_v1/physical_plan/mod.rs
  src/execution_v1/physical_plan/physical_create_table.rs
  src/execution_v1/physical_plan/physical_insert.rs
  src/execution_v1/physical_plan/physical_plan_builder.rs
  src/execution_v1/physical_plan/physical_values.rs
  src/execution_v1/volcano_executor/create_table.rs
  src/execution_v1/volcano_executor/insert.rs
  src/execution_v1/volcano_executor/mod.rs
  src/execution_v1/volcano_executor/values.rs
  src/expression/mod.rs
  src/planner/logical_create_table_plan.rs
  src/planner/logical_insert_plan.rs
  src/planner/mod.rs
  src/planner/operator/create_table.rs
  src/planner/operator/insert.rs
  src/planner/operator/mod.rs
  src/planner/operator/project.rs
  src/planner/operator/values.rs
  src/storage/memory.rs
  src/storage/mod.rs
  src/types/mod.rs
  src/types/value.rs
Labels: enhancement

#36 feat(filter): implement the Filter physical operator
  src/binder/expr.rs
  src/binder/select.rs
  src/db.rs
  src/execution_v1/physical_plan/mod.rs
  src/execution_v1/physical_plan/physical_filter.rs
  src/execution_v1/physical_plan/physical_plan_builder.rs
  src/execution_v1/volcano_executor/filter.rs
  src/execution_v1/volcano_executor/mod.rs
  src/execution_v1/volcano_executor/table_scan.rs
  src/expression/cast.rs
  src/expression/mod.rs
Labels: enhancement
