Repository KipData/KiteSQL, pull requests merged in 2023-10, with the labels that each got.

#73 feat: added marco `implement_from_tuple` to implement ORM function
  Cargo.toml
  README.md
  rust-toolchain
  src/lib.rs
  src/marco/mod.rs
  src/types/mod.rs
  src/types/value.rs
Labels: enhancement

#75 feat(copy): add support for file copying operations in database
  Cargo.toml
  src/binder/copy.rs
  src/binder/create_table.rs
  src/binder/mod.rs
  src/execution/executor/ddl/create_table.rs
  src/execution/executor/dml/copy_from_file.rs
  src/execution/executor/dml/copy_to_file.rs
  src/execution/executor/dml/mod.rs
  src/execution/executor/mod.rs
  src/execution/mod.rs
  src/planner/operator/copy_from_file.rs
  src/planner/operator/copy_to_file.rs
  src/planner/operator/mod.rs
  src/types/errors.rs
  src/types/mod.rs
  src/types/tuple_builder.rs
  tests/data/copy.tbl
  tests/slt/copy.slt
Labels: enhancement

#80 config: `kipdb` version up
  Cargo.toml
  src/execution/executor/dml/copy_from_file.rs
Labels: enhancement

#82 Refactor the executor to support transaction detachment
  Cargo.toml
  src/binder/aggregate.rs
  src/binder/copy.rs
  src/binder/create_table.rs
  src/binder/delete.rs
  src/binder/distinct.rs
  src/binder/drop_table.rs
  src/binder/expr.rs
  src/binder/insert.rs
  src/binder/mod.rs
  src/binder/select.rs
  src/binder/show.rs
  src/binder/truncate.rs
  src/binder/update.rs
  src/catalog/column.rs
  src/db.rs
  src/execution/executor/ddl/create_table.rs
  src/execution/executor/ddl/drop_table.rs
  src/execution/executor/ddl/truncate.rs
  src/execution/executor/dml/copy_from_file.rs
  src/execution/executor/dml/delete.rs
  src/execution/executor/dml/insert.rs
  src/execution/executor/dml/update.rs
  src/execution/executor/dql/aggregate/hash_agg.rs
  src/execution/executor/dql/aggregate/simple_agg.rs
  src/execution/executor/dql/dummy.rs
  src/execution/executor/dql/filter.rs
  src/execution/executor/dql/index_scan.rs
  src/execution/executor/dql/join/hash_join.rs
  src/execution/executor/dql/limit.rs
  src/execution/executor/dql/projection.rs
  src/execution/executor/dql/seq_scan.rs
  src/execution/executor/dql/sort.rs
  src/execution/executor/dql/values.rs
  src/execution/executor/mod.rs
  src/execution/executor/show/show_table.rs
  src/expression/mod.rs
  src/expression/simplify.rs
  src/optimizer/rule/simplification.rs
  src/storage/kip.rs
  src/storage/memory.rs
  src/storage/mod.rs
  src/storage/table_codec.rs
  src/types/mod.rs
  src/types/value.rs
  tests/slt/create.slt
Labels: enhancement, invalid

#88 Test: add many e2e test
  .github/workflows/ci.yml
  Cargo.toml
  rust-toolchain
  src/binder/select.rs
  src/execution/executor/dql/limit.rs
  src/lib.rs
  src/optimizer/rule/pushdown_limit.rs
  src/planner/operator/limit.rs
  src/storage/kip.rs
  src/storage/mod.rs
  tests/slt/insert.slt
  tests/slt/join_left_inner.slt
  tests/slt/limit.slt
  tests/slt/where.slt
Labels: bug, invalid

#92 Feat: add bind_is_null
  src/binder/expr.rs
Labels: enhancement
