Repository KipData/KiteSQL, pull requests merged in 2023-11, with the labels that each got.

#93 Refactor Column Pruning and support where case: `like` and `not like`, `is not null`
  Cargo.toml
  README.md
  rust-toolchain
  src/binder/aggregate.rs
  src/binder/create_table.rs
  src/binder/expr.rs
  src/binder/select.rs
  src/catalog/column.rs
  src/catalog/table.rs
  src/db.rs
  src/execution/executor/dml/copy_from_file.rs
  src/execution/executor/dml/delete.rs
  src/execution/executor/dml/insert.rs
  src/execution/executor/dml/update.rs
  src/execution/executor/dql/projection.rs
  src/expression/evaluator.rs
  src/expression/mod.rs
  src/expression/simplify.rs
  src/expression/value_compute.rs
  src/lib.rs
  src/marco/mod.rs
  src/optimizer/core/opt_expr.rs
  src/optimizer/heuristic/batch.rs
  src/optimizer/heuristic/graph.rs
  src/optimizer/rule/column_pruning.rs
  src/optimizer/rule/combine_operators.rs
  src/optimizer/rule/mod.rs
  src/optimizer/rule/pushdown_limit.rs
  src/optimizer/rule/pushdown_predicates.rs
  src/optimizer/rule/simplification.rs
  src/planner/operator/mod.rs
  src/planner/operator/project.rs
  src/storage/kip.rs
  src/storage/table_codec.rs
  src/types/tuple.rs
  src/types/tuple_builder.rs
  tests/slt/filter.slt
  tests/slt/filter_null.slt
  tests/sqllogictest/src/main.rs
Labels: enhancement, invalid

#95 Support `In` expression
  .github/workflows/ci.yml
  Cargo.toml
  README.md
  src/binder/aggregate.rs
  src/binder/expr.rs
  src/db.rs
  src/execution/executor/dql/aggregate/hash_agg.rs
  src/execution/executor/dql/aggregate/simple_agg.rs
  src/execution/executor/dql/filter.rs
  src/execution/executor/dql/join/hash_join.rs
  src/execution/executor/dql/projection.rs
  src/execution/executor/dql/sort.rs
  src/expression/evaluator.rs
  src/expression/mod.rs
  src/optimizer/rule/column_pruning.rs
  src/optimizer/rule/pushdown_predicates.rs
  src/planner/operator/mod.rs
  src/storage/kip.rs
  src/storage/mod.rs
  tests/slt/filter.slt
Labels: documentation, enhancement

#99 fix CacheError
  .github/workflows/ci.yml
  src/storage/mod.rs
Labels: bug

#103 Support Default, constraints of CreateTable and Fix
  Cargo.toml
  src/binder/aggregate.rs
  src/binder/copy.rs
  src/binder/create_table.rs
  src/binder/distinct.rs
  src/binder/drop_table.rs
  src/binder/expr.rs
  src/binder/insert.rs
  src/binder/mod.rs
  src/binder/select.rs
  src/binder/truncate.rs
  src/binder/update.rs
  src/catalog/column.rs
  src/catalog/mod.rs
  src/catalog/root.rs
  src/catalog/table.rs
  src/db.rs
  src/execution/executor/ddl/create_table.rs
  src/execution/executor/dml/copy_from_file.rs
  src/execution/executor/dml/delete.rs
  src/execution/executor/dml/insert.rs
  src/execution/executor/dml/update.rs
  src/execution/executor/dql/aggregate/hash_agg.rs
  src/execution/executor/dql/aggregate/min_max.rs
  src/execution/executor/dql/aggregate/sum.rs
  src/execution/executor/dql/index_scan.rs
  src/execution/executor/dql/join/hash_join.rs
  src/execution/executor/dql/seq_scan.rs
  src/expression/evaluator.rs
  src/expression/mod.rs
  src/expression/simplify.rs
  src/expression/value_compute.rs
  src/marco/mod.rs
  src/optimizer/heuristic/graph.rs
  src/optimizer/heuristic/matcher.rs
  src/optimizer/rule/pushdown_limit.rs
  src/optimizer/rule/pushdown_predicates.rs
  src/optimizer/rule/simplification.rs
  src/planner/operator/aggregate.rs
  src/planner/operator/create_table.rs
  src/planner/operator/filter.rs
  src/planner/operator/join.rs
  src/planner/operator/limit.rs
  src/planner/operator/scan.rs
  src/storage/kip.rs
  src/storage/mod.rs
  src/storage/table_codec.rs
  src/types/index.rs
  src/types/mod.rs
  src/types/tuple.rs
  src/types/value.rs
  tests/slt/basic_test.slt
  tests/slt/create.slt
  tests/slt/insert.slt
Labels: bug, enhancement, invalid
