Repository KipData/KiteSQL, pull requests merged in 2024-12, with the labels that each got.

#250 Perf/issue 155
  README.md
  src/catalog/table.rs
  src/execution/ddl/add_column.rs
  src/execution/ddl/create_index.rs
  src/execution/dml/analyze.rs
  src/execution/dml/delete.rs
  src/execution/dml/insert.rs
  src/execution/dml/update.rs
  src/expression/evaluator.rs
  src/expression/range_detacher.rs
  src/optimizer/core/histogram.rs
  src/optimizer/core/memo.rs
  src/optimizer/core/statistics_meta.rs
  src/optimizer/rule/normalization/pushdown_predicates.rs
  src/serdes/data_value.rs
  src/storage/mod.rs
  src/storage/rocksdb.rs
  src/storage/table_codec.rs
  src/types/evaluator/tuple.rs
  src/types/index.rs
  src/types/tuple_builder.rs
  src/types/value.rs
  tests/sqllogictest/Cargo.toml
  tpcc/src/README.md
  tpcc/src/load.rs
  tpcc/src/main.rs
Labels: enhancement, perf

#252 chore: rollback `https://github.com/KipData/FnckSQL/pull/191`
  src/binder/expr.rs
  src/binder/mod.rs
Labels: invalid

#253 docs: README
  README.md
  docs/features.md
  tpcc/README.md
Labels: documentation

#254 Perf/tpcc
  Cargo.toml
  README.md
  src/binder/copy.rs
  src/catalog/table.rs
  src/db.rs
  src/execution/ddl/add_column.rs
  src/execution/ddl/create_index.rs
  src/execution/ddl/create_table.rs
  src/execution/ddl/create_view.rs
  src/execution/ddl/drop_column.rs
  src/execution/ddl/drop_table.rs
  src/execution/ddl/drop_view.rs
  src/execution/ddl/truncate.rs
  src/execution/dml/analyze.rs
  src/execution/dml/copy_from_file.rs
  src/execution/dml/copy_to_file.rs
  src/execution/dml/delete.rs
  src/execution/dml/insert.rs
  src/execution/dml/update.rs
  src/execution/dql/aggregate/hash_agg.rs
  src/execution/dql/aggregate/simple_agg.rs
  src/execution/dql/describe.rs
  src/execution/dql/dummy.rs
  src/execution/dql/explain.rs
  src/execution/dql/filter.rs
  src/execution/dql/function_scan.rs
  src/execution/dql/index_scan.rs
  src/execution/dql/join/hash_join.rs
  src/execution/dql/join/nested_loop_join.rs
  src/execution/dql/limit.rs
  src/execution/dql/projection.rs
  src/execution/dql/seq_scan.rs
  src/execution/dql/show_table.rs
  src/execution/dql/sort.rs
  src/execution/dql/union.rs
  src/execution/dql/values.rs
  src/execution/mod.rs
  src/function/numbers.rs
  src/macros/mod.rs
  src/planner/operator/copy_from_file.rs
  src/storage/mod.rs
  src/storage/rocksdb.rs
  src/storage/table_codec.rs
  src/types/tuple.rs
  src/types/tuple_builder.rs
  tests/macros-test/src/main.rs
  tpcc/Cargo.toml
  tpcc/README.md
Labels: enhancement

#256 chore: supplement decimal’s `memcomparable` encode
  README.md
  src/bin/server.rs
  src/binder/alter_table.rs
  src/binder/copy.rs
  src/binder/create_table.rs
  src/binder/expr.rs
  src/binder/mod.rs
  src/binder/select.rs
  src/db.rs
  src/errors.rs
  src/planner/operator/mod.rs
  src/storage/mod.rs
  src/storage/rocksdb.rs
  src/storage/table_codec.rs
  src/types/value.rs
  tests/slt/where_by_index.slt
  tpcc/README.md
Labels: enhancement, invalid

#258 chore: refactor backend handlers and update `pgwire` dependency.
  Cargo.toml
  src/bin/server.rs
Labels: enhancement
