Repository KipData/KiteSQL, pull requests merged in 2024-03, with the labels that each got.

#148 test: add `where_by_index.slt` to verify the correctness of `IndexScan`
  src/expression/simplify.rs
  src/optimizer/rule/normalization/pushdown_predicates.rs
  src/storage/mod.rs
  tests/slt/where_by_index.slt
  tests/sqllogictest/Cargo.toml
  tests/sqllogictest/src/main.rs
Labels: test

#149 fix: Check `HashJoin` exists on keys and `CNF` and `DNF` inference
  Cargo.toml
  src/binder/select.rs
  src/execution/volcano/dql/index_scan.rs
  src/execution/volcano/dql/join/hash_join.rs
  src/execution/volcano/mod.rs
  src/expression/simplify.rs
  src/optimizer/core/memo.rs
  src/optimizer/heuristic/graph.rs
  src/optimizer/rule/implementation/dql/scan.rs
  src/optimizer/rule/normalization/pushdown_predicates.rs
  src/planner/operator/scan.rs
  src/storage/kip.rs
  src/storage/mod.rs
  src/types/index.rs
  tests/slt/crdb/sqlite.slt
  tests/slt/sql_2016/E061_09.slt
  tests/slt/sql_2016/F041_08.slt
  tests/slt/subquery.slt
  tests/slt/where_by_index.slt
Labels: bug, invalid

#150 fix: range detection error when nesting `and` & `or`
  Cargo.toml
  src/expression/simplify.rs
  src/optimizer/rule/normalization/simplification.rs
  tests/slt/dummy.slt
  tests/slt/where_by_index.slt
Labels: bug

#151 refactor `RangeDetacher`
  src/execution/volcano/dql/index_scan.rs
  src/execution/volcano/mod.rs
  src/expression/mod.rs
  src/expression/range_detacher.rs
  src/expression/simplify.rs
  src/optimizer/core/cm_sketch.rs
  src/optimizer/core/column_meta.rs
  src/optimizer/core/histogram.rs
  src/optimizer/core/memo.rs
  src/optimizer/rule/implementation/dql/scan.rs
  src/optimizer/rule/normalization/pushdown_predicates.rs
  src/optimizer/rule/normalization/simplification.rs
  src/planner/operator/scan.rs
  src/storage/kip.rs
  src/storage/mod.rs
  src/types/index.rs
  tests/slt/where_by_index.slt
Labels: enhancement, invalid

#152 fix: `RangeDetacher::check_or` incorrect handling of case: `c1 > 1 or c2 > 1`
  src/expression/range_detacher.rs
Labels: bug

#153 feat(type): add support for double precision
  src/types/mod.rs
  tests/slt/sql_2016/E011_02.slt
Labels: enhancement

#158 fmt: clear the feature `codegen` and streamline the code
  Cargo.toml
  benchmarks/query_benchmark.rs
  src/binder/copy.rs
  src/binder/create_index.rs
  src/binder/create_table.rs
  src/binder/expr.rs
  src/catalog/table.rs
  src/db.rs
  src/errors.rs
  src/execution/codegen/dql/aggregate/hash_agg.rs
  src/execution/codegen/dql/aggregate/mod.rs
  src/execution/codegen/dql/aggregate/simple_agg.rs
  src/execution/codegen/dql/filter.rs
  src/execution/codegen/dql/index_scan.rs
  src/execution/codegen/dql/join/hash_join.rs
  src/execution/codegen/dql/join/mod.rs
  src/execution/codegen/dql/limit.rs
  src/execution/codegen/dql/mod.rs
  src/execution/codegen/dql/projection.rs
  src/execution/codegen/dql/seq_scan.rs
  src/execution/codegen/dql/sort.rs
  src/execution/codegen/marcos.rs
  src/execution/codegen/mod.rs
  src/execution/mod.rs
  src/execution/volcano/dml/copy_from_file.rs
  src/optimizer/core/statistics_meta.rs
  src/storage/mod.rs
  src/storage/table_codec.rs
  src/types/mod.rs
  tests/sqllogictest/Cargo.toml
Labels: bug, invalid

#159 feat: add support for `POSITION()`
  src/binder/aggregate.rs
  src/binder/expr.rs
  src/expression/evaluator.rs
  src/expression/mod.rs
  src/expression/range_detacher.rs
  src/expression/simplify.rs
  tests/slt/sql_2016/E021_11.slt
Labels: enhancement

#161 fix: fucntion `substring` for out of bounds error
  src/binder/select.rs
  src/expression/evaluator.rs
  src/planner/mod.rs
  src/planner/operator/mod.rs
  src/planner/operator/union.rs
  tests/slt/substring.slt
  tests/slt/tuple.slt
  tests/slt/union.slt
  tests/slt/update.slt
Labels: enhancement

#164 feat: add support for nested loop join
  src/binder/expr.rs
  src/binder/select.rs
  src/execution/volcano/dql/join/mod.rs
  src/execution/volcano/dql/join/nested_loop_join.rs
  src/execution/volcano/mod.rs
  src/expression/mod.rs
  src/optimizer/rule/implementation/dql/join.rs
  src/optimizer/rule/implementation/mod.rs
  src/optimizer/rule/normalization/combine_operators.rs
  src/planner/operator/mod.rs
  tests/slt/crdb/sqlite.slt
  tests/slt/join.slt
  tests/slt/sql_2016/E061_09.slt
  tests/slt/sql_2016/F041_08.slt
  tests/slt/subquery.slt
Labels: enhancement

#167 perf: Optimize `StatisticsMetaLoader::load`
  src/catalog/table.rs
  src/execution/volcano/dml/analyze.rs
  src/execution/volcano/dql/show_table.rs
  src/optimizer/core/statistics_meta.rs
  src/optimizer/rule/implementation/dql/scan.rs
  src/planner/mod.rs
  src/storage/kip.rs
  src/storage/mod.rs
  src/storage/table_codec.rs
Labels: perf

#172 doc: add Cross Join for DQL and Contributors
  Cargo.toml
  README.md
Labels: documentation

#173 fix: In multi-level nested subquery, the field relationships of different tables are wrong
  src/binder/create_table.rs
  src/binder/expr.rs
  src/binder/mod.rs
  src/db.rs
  src/errors.rs
  src/optimizer/core/memo.rs
  tests/slt/subquery.slt
Labels: bug

#174 feat: add `DataType::Char` and add `LEN` to `Describe`
  README.md
  src/bin/server.rs
  src/execution/volcano/ddl/add_column.rs
  src/execution/volcano/ddl/drop_column.rs
  src/execution/volcano/dml/copy_from_file.rs
  src/execution/volcano/dml/insert.rs
  src/execution/volcano/dml/update.rs
  src/execution/volcano/dql/describe.rs
  src/expression/value_compute.rs
  src/optimizer/core/histogram.rs
  src/planner/mod.rs
  src/storage/kip.rs
  src/storage/mod.rs
  src/storage/table_codec.rs
  src/types/mod.rs
  src/types/tuple.rs
  src/types/value.rs
  tests/slt/describe.slt
  tests/slt/dummy.slt
  tests/slt/insert.slt
  tests/slt/sql_2016/E021_01.slt
  tests/slt/sql_2016/E021_02.slt
  tests/slt/sql_2016/E021_10.slt
Labels: enhancement

#177 Fix/serial ddl
  Cargo.toml
  src/binder/copy.rs
  src/binder/mod.rs
  src/db.rs
  src/storage/kip.rs
  tests/slt/basic_test.slt
Labels: bug, enhancement

#180 feat: support `Expression` on `Default`
  Cargo.toml
  src/binder/create_table.rs
  src/binder/insert.rs
  src/binder/update.rs
  src/catalog/column.rs
  src/db.rs
  src/errors.rs
  src/execution/volcano/ddl/add_column.rs
  src/execution/volcano/dml/insert.rs
  src/execution/volcano/dql/describe.rs
  src/expression/function.rs
  src/expression/mod.rs
  src/marcos/mod.rs
  src/storage/kip.rs
  src/types/tuple.rs
  tests/slt/create.slt
Labels: enhancement

#181 Feat: add Function: `current_date` & add Type: `LogicalType::Time`
  README.md
  src/bin/server.rs
  src/db.rs
  src/expression/value_compute.rs
  src/lib.rs
  src/marcos/mod.rs
  src/optimizer/core/histogram.rs
  src/storage/table_codec.rs
  src/types/mod.rs
  src/types/tuple.rs
  src/types/value.rs
  src/udf/current_date.rs
  src/udf/mod.rs
  tests/slt/basic_test.slt
  tests/slt/sql_2016/E141_07.slt
  tests/slt/sql_2016/F051_06.slt
Labels: enhancement

#184 feat: support `Octets` for `Char/Varchar`
  Cargo.toml
  README.md
  src/bin/server.rs
  src/binder/create_table.rs
  src/binder/expr.rs
  src/catalog/column.rs
  src/execution/volcano/dml/analyze.rs
  src/execution/volcano/dml/copy_from_file.rs
  src/execution/volcano/dql/describe.rs
  src/execution/volcano/dql/explain.rs
  src/execution/volcano/dql/show_table.rs
  src/expression/evaluator.rs
  src/expression/mod.rs
  src/expression/value_compute.rs
  src/marcos/mod.rs
  src/optimizer/core/histogram.rs
  src/optimizer/rule/normalization/column_pruning.rs
  src/storage/table_codec.rs
  src/types/mod.rs
  src/types/tuple.rs
  src/types/tuple_builder.rs
  src/types/value.rs
  tests/slt/char.slt
  tests/slt/sql_2016/E021_01.slt
  tests/slt/sql_2016/E021_02.slt
Labels: bug, enhancement

#185 feat: Add docker support
  Dockerfile
  README.md
Labels: enhancement

#189 fix: memcomparable for `DataValue::Tuple`
  src/storage/table_codec.rs
  src/types/mod.rs
  src/types/value.rs
Labels: bug

#191 fix: bind correlated subqueries
  src/binder/expr.rs
  src/binder/mod.rs
Labels: bug

#193 refactor: optimize the implementation of `IndexIter`
  src/storage/kip.rs
  src/storage/mod.rs
Labels: enhancement

#195 refactor: eliminate the deprecation warning
  src/types/value.rs
Labels: invalid
